// Comprehensive Question Bank containing 21 topics (20 technical + 1 HR) with exactly 20 questions each.
// Difficulty mapped as: Beginner (Easy), Intermediate (Medium), Advanced (Hard)

const topicsData = [
  { title: 'Java', description: 'Core Java, OOPs concepts, Collections, Multithreading, JVM, and Exception Handling.' },
  { title: 'JavaScript', description: 'ES6+ syntax, Closures, Event Loop, Promises, Async/Await, DOM manipulation, and Prototypes.' },
  { title: 'React', description: 'Virtual DOM, JSX, Hooks (useState, useEffect, useContext), State Management, Lifecycle methods, and Performance.' },
  { title: 'Node.js', description: 'Event Loop, Streams, Buffer, Express framework, Middleware, REST APIs, and Event Emitters.' },
  { title: 'MongoDB', description: 'NoSQL architecture, Document queries, Indexes, Aggregations, Mongoose, and Replication.' },
  { title: 'SQL', description: 'Relational databases, Joins, Subqueries, Normalization, Transactions, ACID properties, and DDL/DML commands.' },
  { title: 'DBMS', description: 'Database management systems, Keys (Primary, Foreign), ER Diagrams, Indexing, and Concurrency Control.' },
  { title: 'Operating System', description: 'Process management, Threading, CPU Scheduling, Deadlocks, Memory Management, Virtual Memory, and System Calls.' },
  { title: 'Computer Networks', description: 'OSI Model layers, TCP/UDP protocols, IP Addressing, DNS, HTTP/HTTPS handshake, and Firewalls.' },
  { title: 'OOP', description: 'Inheritance, Polymorphism, Encapsulation, Abstraction, Interfaces, Abstract classes, and SOLID principles.' },
  { title: 'DSA', description: 'Arrays, Linked Lists, Stacks, Queues, Trees, Graphs, Sorting & Searching, and Dynamic Programming.' },
  { title: 'HTML & CSS', description: 'Semantic elements, Box Model, Flexbox, Grid, Responsive Design, CSS variables, and preprocessors.' },
  { title: 'Python', description: 'Data structures, list comprehensions, decorators, generators, OOP in Python, memory management, and GIL.' },
  { title: 'Git & GitHub', description: 'Version control, branching strategies, merging vs rebasing, stashing, cherry-picking, and pull requests.' },
  { title: 'Docker', description: 'Containers vs virtual machines, Dockerfile instructions, image layers, volumes, networking, and Docker Compose.' },
  { title: 'REST APIs', description: 'HTTP methods, status codes, statelessness, URI design, versioning, security, and pagination.' },
  { title: 'Cloud Computing', description: 'IaaS/PaaS/SaaS, AWS core services, load balancing, auto-scaling, cloud security, and serverless architecture.' },
  { title: 'System Design', description: 'Scalability, load balancing, caching, database sharding, microservices, and message queues.' },
  { title: 'Cyber Security', description: 'Authentication vs Authorization, encryption, hashing, common vulnerabilities (SQLi, XSS, CSRF), and HTTPS.' },
  { title: 'Agile & DevOps', description: 'Scrum framework, CI/CD pipelines, IaC, monitoring, testing strategies, and software development lifecycle.' },
  { title: 'HR Questions', description: 'Behavioral assessment, Situational questions, Teamwork, Weaknesses & Strengths, and Conflict Resolution.' }
];

const questionsData = {
  'Java': [
    { question: 'What are the main differences between JDK, JRE, and JVM?', difficulty: 'Beginner' },
    { question: 'Explain the difference between path and classpath in Java.', difficulty: 'Beginner' },
    { question: 'What is the "final" keyword in Java? How is it used with variables, methods, and classes?', difficulty: 'Beginner' },
    { question: 'Explain Method Overloading vs Method Overriding in Java.', difficulty: 'Beginner' },
    { question: 'What is the difference between String, StringBuffer, and StringBuilder?', difficulty: 'Beginner' },
    { question: 'What are wrapper classes in Java, and what is Autoboxing/Unboxing?', difficulty: 'Beginner' },
    { question: 'What is the purpose of the "static" keyword in Java?', difficulty: 'Beginner' },
    { question: 'Explain the internal working of HashMap in Java. How are collisions handled?', difficulty: 'Intermediate' },
    { question: 'What is the difference between Abstract Classes and Interfaces in Java?', difficulty: 'Intermediate' },
    { question: 'How does Exception Handling work in Java? Contrast checked vs unchecked exceptions.', difficulty: 'Intermediate' },
    { question: 'What is Multithreading in Java, and how do you achieve synchronization between threads?', difficulty: 'Intermediate' },
    { question: 'Explain the Java Collection framework hierarchy. Highlight differences between List, Set, and Map.', difficulty: 'Intermediate' },
    { question: 'What is serialization and deserialization in Java? What is the role of transient variables?', difficulty: 'Intermediate' },
    { question: 'What are Generics in Java, and why do we use them?', difficulty: 'Intermediate' },
    { question: 'Explain the JVM memory structure. What is garbage collection and how does it work?', difficulty: 'Advanced' },
    { question: 'What are the different types of garbage collectors in Java (G1, CMS, ZGC)?', difficulty: 'Advanced' },
    { question: 'Explain the Java Memory Model (JMM) and the purpose of the volatile keyword.', difficulty: 'Advanced' },
    { question: 'What are memory leaks in Java, and how can they be detected and avoided?', difficulty: 'Advanced' },
    { question: 'Explain the concept of reflection in Java. What are its use cases and drawbacks?', difficulty: 'Advanced' },
    { question: 'How does CompletableFuture work in Java for asynchronous programming?', difficulty: 'Advanced' }
  ],
  'JavaScript': [
    { question: 'What are the primitive data types in JavaScript?', difficulty: 'Beginner' },
    { question: 'Explain the difference between "==" and "===" in JavaScript.', difficulty: 'Beginner' },
    { question: 'Compare "var", "let", and "const" scope details and hoisting behavior.', difficulty: 'Beginner' },
    { question: 'What is the purpose of the "typeof" and "instanceof" operators?', difficulty: 'Beginner' },
    { question: 'What are template literals and arrow functions introduced in ES6?', difficulty: 'Beginner' },
    { question: 'What is the difference between null and undefined in JavaScript?', difficulty: 'Beginner' },
    { question: 'What are array helper methods like map, filter, and reduce in JS?', difficulty: 'Beginner' },
    { question: 'What is a Closure in JavaScript, and what are its practical use cases?', difficulty: 'Intermediate' },
    { question: 'Explain how the JavaScript Event Loop works, covering call stack, callback queue, and microtask queue.', difficulty: 'Intermediate' },
    { question: 'How do Promises work? Explain the difference between promise chains and async/await syntax.', difficulty: 'Intermediate' },
    { question: 'What is the purpose of bind, call, and apply methods in JavaScript?', difficulty: 'Intermediate' },
    { question: 'Explain event bubbling, event capturing, and event delegation in JavaScript.', difficulty: 'Intermediate' },
    { question: 'What is the difference between deep copy and shallow copy? How do you achieve them in JS?', difficulty: 'Intermediate' },
    { question: 'Explain the "this" keyword behavior in different execution contexts.', difficulty: 'Intermediate' },
    { question: 'What is prototype-based inheritance in JavaScript? How does it differ from classical class-based inheritance?', difficulty: 'Advanced' },
    { question: 'Explain the concept of Currying in JavaScript with an example.', difficulty: 'Advanced' },
    { question: 'What is a Memory Leak in JavaScript, and what are the common causes (e.g. global variables, closures)?', difficulty: 'Advanced' },
    { question: 'Explain strict mode in JS ("use strict") and its benefits.', difficulty: 'Advanced' },
    { question: 'How does the V8 engine compile and optimize JavaScript code (JIT compilation)?', difficulty: 'Advanced' },
    { question: 'What are generator functions in JS, and how do they work with the yield keyword?', difficulty: 'Advanced' }
  ],
  'React': [
    { question: 'What is React, and what are its key features?', difficulty: 'Beginner' },
    { question: 'Explain the concept of the Virtual DOM and how React reconciliation works.', difficulty: 'Beginner' },
    { question: 'What is JSX, and is it mandatory for writing React applications?', difficulty: 'Beginner' },
    { question: 'Explain the difference between functional components and class components.', difficulty: 'Beginner' },
    { question: 'What are props and state in React? Highlight the key differences.', difficulty: 'Beginner' },
    { question: 'What are keys in React, and why are they important when rendering lists?', difficulty: 'Beginner' },
    { question: 'Explain conditional rendering in React with examples.', difficulty: 'Beginner' },
    { question: 'Explain React Hooks. Detail the use cases of useState and useEffect.', difficulty: 'Intermediate' },
    { question: 'What is the useContext hook, and how does it help solve prop drilling?', difficulty: 'Intermediate' },
    { question: 'What are custom hooks in React, and when should you write one?', difficulty: 'Intermediate' },
    { question: 'What is the difference between controlled and uncontrolled components?', difficulty: 'Intermediate' },
    { question: 'Explain state management. When would you choose Redux or Context API over local state?', difficulty: 'Intermediate' },
    { question: 'Explain the React component lifecycle methods in class components and their hook equivalents.', difficulty: 'Intermediate' },
    { question: 'What are forms handling options in React (controlled vs uncontrolled)?', difficulty: 'Intermediate' },
    { question: 'How does React Fiber work, and what problem does it solve?', difficulty: 'Advanced' },
    { question: 'Explain React performance optimization techniques (useMemo, useCallback, React.memo).', difficulty: 'Advanced' },
    { question: 'What is Code Splitting in React, and how is it implemented using lazy and Suspense?', difficulty: 'Advanced' },
    { question: 'Explain Server-Side Rendering (SSR) vs Client-Side Rendering (CSR) vs Static Site Generation (SSG) in React ecosystems.', difficulty: 'Advanced' },
    { question: 'What are React Portals, and when would you use them?', difficulty: 'Advanced' },
    { question: 'Explain Higher-Order Components (HOC) and Render Props patterns in React.', difficulty: 'Advanced' }
  ],
  'Node.js': [
    { question: 'What is Node.js, and is it a programming language or a runtime environment?', difficulty: 'Beginner' },
    { question: 'Explain the asynchronous, single-threaded, and non-blocking nature of Node.js.', difficulty: 'Beginner' },
    { question: 'What is npm (Node Package Manager) and package.json?', difficulty: 'Beginner' },
    { question: 'Explain the role of Node.js modules (CommonJS vs ES Modules).', difficulty: 'Beginner' },
    { question: 'What is the purpose of the path and fs modules in Node.js?', difficulty: 'Beginner' },
    { question: 'Explain the difference between console.log, console.error, and console.warn.', difficulty: 'Beginner' },
    { question: 'What is the purpose of package-lock.json?', difficulty: 'Beginner' },
    { question: 'Explain the Node.js Event Loop. What are its phases?', difficulty: 'Intermediate' },
    { question: 'What is Express.js, and how does routing work in Express?', difficulty: 'Intermediate' },
    { question: 'What is Middleware in Express? Write a simple custom logging middleware.', difficulty: 'Intermediate' },
    { question: 'What are Event Emitters in Node.js? Give a use case.', difficulty: 'Intermediate' },
    { question: 'Explain the difference between setImmediate(), setTimeout(), and process.nextTick().', difficulty: 'Intermediate' },
    { question: 'How do you handle files using streams and buffers in Node.js? Why are they efficient?', difficulty: 'Intermediate' },
    { question: 'How do you handle errors globally in an Express application?', difficulty: 'Intermediate' },
    { question: 'Explain the clustering model in Node.js. How does it help scale applications?', difficulty: 'Advanced' },
    { question: 'What are Worker Threads in Node.js, and when should you use them instead of clustering?', difficulty: 'Advanced' },
    { question: 'Explain memory management and debugging memory leaks in a production Node.js server.', difficulty: 'Advanced' },
    { question: 'How do streams backpressure work in Node.js? How do you handle it?', difficulty: 'Advanced' },
    { question: 'Compare event-driven architecture with multi-threaded architecture in high I/O applications.', difficulty: 'Advanced' },
    { question: 'Explain security best practices for Node.js (e.g. helmet, rate limiting, dependency auditing).', difficulty: 'Advanced' }
  ],
  'MongoDB': [
    { question: 'What is MongoDB, and what type of database is it?', difficulty: 'Beginner' },
    { question: 'Explain the difference between SQL and NoSQL databases.', difficulty: 'Beginner' },
    { question: 'What is a Document and a Collection in MongoDB? What is their relational equivalent?', difficulty: 'Beginner' },
    { question: 'What is BSON, and how does it differ from JSON?', difficulty: 'Beginner' },
    { question: 'What is Mongoose, and why is it used in Node.js applications?', difficulty: 'Beginner' },
    { question: 'How do you perform basic CRUD operations in MongoDB?', difficulty: 'Beginner' },
    { question: 'What is the role of the default "_id" field in MongoDB documents?', difficulty: 'Beginner' },
    { question: 'What are Indexes in MongoDB, and why are they used? How do you create one?', difficulty: 'Intermediate' },
    { question: 'Explain the MongoDB Aggregation Pipeline and some common stages (like $match, $group, $project).', difficulty: 'Intermediate' },
    { question: 'What are Embedded Documents vs Reference Documents in MongoDB? When to use which?', difficulty: 'Intermediate' },
    { question: 'How does Mongoose middleware (pre and post hooks) work?', difficulty: 'Intermediate' },
    { question: 'Explain transactions in MongoDB. Are they supported, and how do you use them?', difficulty: 'Intermediate' },
    { question: 'What is the difference between $set and replacing a document in an update query?', difficulty: 'Intermediate' },
    { question: 'What is gridFS in MongoDB, and what is its purpose?', difficulty: 'Intermediate' },
    { question: 'Explain replication in MongoDB (Replica Sets) and how high availability is achieved.', difficulty: 'Advanced' },
    { question: 'What is Sharding in MongoDB? Explain the components of a sharded cluster.', difficulty: 'Advanced' },
    { question: 'How do database indexes impact write performance vs read performance in MongoDB?', difficulty: 'Advanced' },
    { question: 'Explain storage engines in MongoDB, specifically WiredTiger.', difficulty: 'Advanced' },
    { question: 'How do you design a database schema in MongoDB for a massive e-commerce platform with high concurrency?', difficulty: 'Advanced' },
    { question: 'How does MongoDB handle horizontal scaling compared to relational databases?', difficulty: 'Advanced' }
  ],
  'SQL': [
    { question: 'What is SQL, and what is a relational database?', difficulty: 'Beginner' },
    { question: 'What is the difference between DDL, DML, and DCL commands?', difficulty: 'Beginner' },
    { question: 'Explain the primary key and foreign key concepts.', difficulty: 'Beginner' },
    { question: 'What is the difference between CHAR and VARCHAR data types?', difficulty: 'Beginner' },
    { question: 'What is the difference between WHERE and HAVING clauses?', difficulty: 'Beginner' },
    { question: 'What are SQL constraints? List some common constraints.', difficulty: 'Beginner' },
    { question: 'Explain the difference between SELECT DISTINCT and GROUP BY.', difficulty: 'Beginner' },
    { question: 'Explain the different types of Joins in SQL (Inner, Left, Right, Full).', difficulty: 'Intermediate' },
    { question: 'What is database normalization? Explain 1NF, 2NF, and 3NF.', difficulty: 'Intermediate' },
    { question: 'What are SQL Subqueries? Contrast nested subqueries with correlated subqueries.', difficulty: 'Intermediate' },
    { question: 'What is a SQL View? What are the advantages of using views?', difficulty: 'Intermediate' },
    { question: 'Explain the difference between UNION and UNION ALL.', difficulty: 'Intermediate' },
    { question: 'What is an Index in SQL? Explain Clustered vs Non-Clustered Indexes.', difficulty: 'Intermediate' },
    { question: 'What are Aggregate Functions in SQL? Give three examples.', difficulty: 'Intermediate' },
    { question: 'Explain ACID properties in SQL databases with practical examples.', difficulty: 'Advanced' },
    { question: 'What is a Transaction? Explain transaction isolation levels (Read Uncommitted, Read Committed, Repeatable Read, Serializable).', difficulty: 'Advanced' },
    { question: 'What are database deadlocks, and how can they be resolved or prevented in SQL?', difficulty: 'Advanced' },
    { question: 'Explain query optimization. How do you analyze a slow query using EXPLAIN?', difficulty: 'Advanced' },
    { question: 'What are Triggers and Stored Procedures? When should you avoid using them?', difficulty: 'Advanced' },
    { question: 'Explain the difference between row-oriented and column-oriented database storage.', difficulty: 'Advanced' }
  ],
  'DBMS': [
    { question: 'What is a DBMS (Database Management System)? What are its advantages over file systems?', difficulty: 'Beginner' },
    { question: 'What are the main differences between DBMS and RDBMS?', difficulty: 'Beginner' },
    { question: 'What is a Schema? Explain physical vs logical schema.', difficulty: 'Beginner' },
    { question: 'What is data independence, and why is it important?', difficulty: 'Beginner' },
    { question: 'What are the different levels of database abstraction?', difficulty: 'Beginner' },
    { question: 'Explain what a primary key, candidate key, and super key are.', difficulty: 'Beginner' },
    { question: 'What is a weak entity set in database modeling?', difficulty: 'Beginner' },
    { question: 'What is an Entity-Relationship (ER) Diagram? Explain its components.', difficulty: 'Intermediate' },
    { question: 'Explain the concept of Functional Dependency in normalization.', difficulty: 'Intermediate' },
    { question: 'What is Concurrency Control? Why is it needed in DBMS?', difficulty: 'Intermediate' },
    { question: 'Explain Lock-Based Protocols for concurrency (Shared and Exclusive locks).', difficulty: 'Intermediate' },
    { question: 'What is the Two-Phase Locking (2PL) protocol? How does it guarantee serializability?', difficulty: 'Intermediate' },
    { question: 'Explain Referential Integrity and Cascade Delete constraints.', difficulty: 'Intermediate' },
    { question: 'What is a Log-Based Recovery mechanism in DBMS?', difficulty: 'Intermediate' },
    { question: 'Explain the concept of Conflict Serializability and how it is checked using precedence graphs.', difficulty: 'Advanced' },
    { question: 'What is the difference between Write-Ahead Logging (WAL) and Shadow Paging?', difficulty: 'Advanced' },
    { question: 'Explain the CAP Theorem and its implications for distributed database systems.', difficulty: 'Advanced' },
    { question: 'What is Multiversion Concurrency Control (MVCC), and how is it used in modern databases?', difficulty: 'Advanced' },
    { question: 'Explain the differences between B-Tree and B+ Tree indexing. Why are B+ Trees preferred for database storage?', difficulty: 'Advanced' },
    { question: 'How do database checkpoints minimize recovery time during a system crash?', difficulty: 'Advanced' }
  ],
  'Operating System': [
    { question: 'What is an Operating System (OS)? What are its core responsibilities?', difficulty: 'Beginner' },
    { question: 'Explain the difference between a Process and a Thread.', difficulty: 'Beginner' },
    { question: 'What is Multitasking, Multiprogramming, and Multiprocessing?', difficulty: 'Beginner' },
    { question: 'What is a System Call? Name three common system calls.', difficulty: 'Beginner' },
    { question: 'What is the kernel of an OS? Contrast monolithic vs microkernel architectures.', difficulty: 'Beginner' },
    { question: 'Explain the states of a Process (New, Ready, Running, Waiting, Terminated).', difficulty: 'Beginner' },
    { question: 'What is context switching in operating systems?', difficulty: 'Beginner' },
    { question: 'Explain different CPU Scheduling Algorithms (FCFS, SJF, Round Robin, Priority).', difficulty: 'Intermediate' },
    { question: 'What is a Deadlock? Explain the four necessary conditions for a deadlock to occur.', difficulty: 'Intermediate' },
    { question: 'Explain Virtual Memory and Paging. What is the role of the Page Table?', difficulty: 'Intermediate' },
    { question: 'What is Page Fault? What happens when a page fault occurs?', difficulty: 'Intermediate' },
    { question: 'What is Thrashing in memory management? How can it be prevented?', difficulty: 'Intermediate' },
    { question: 'Explain Inter-Process Communication (IPC) and common methods (shared memory, message passing).', difficulty: 'Intermediate' },
    { question: 'What is a Semaphore? Contrast binary semaphores with counting semaphores.', difficulty: 'Intermediate' },
    { question: 'Explain the Critical Section Problem and the requirements for a valid solution (Mutual Exclusion, Progress, Bounded Waiting).', difficulty: 'Advanced' },
    { question: 'What is the Banker\'s Algorithm? How is it used for Deadlock Avoidance?', difficulty: 'Advanced' },
    { question: 'Explain Page Replacement Algorithms (FIFO, LRU, Optimal). Highlight Belady\'s Anomaly.', difficulty: 'Advanced' },
    { question: 'What is RAID? Explain RAID 0, RAID 1, RAID 5, and RAID 10.', difficulty: 'Advanced' },
    { question: 'Explain cache coherence in multi-core processor operating systems.', difficulty: 'Advanced' },
    { question: 'What is the translation lookaside buffer (TLB) and how does it optimize virtual memory lookup?', difficulty: 'Advanced' }
  ],
  'Computer Networks': [
    { question: 'What is a Computer Network? Contrast LAN, MAN, and WAN.', difficulty: 'Beginner' },
    { question: 'Explain the OSI Model. Name all the 7 layers in sequence.', difficulty: 'Beginner' },
    { question: 'What is the TCP/IP Model, and how does it compare to the OSI Model?', difficulty: 'Beginner' },
    { question: 'What is an IP Address? Contrast IPv4 and IPv6.', difficulty: 'Beginner' },
    { question: 'Explain the purpose of routers, switches, and hubs.', difficulty: 'Beginner' },
    { question: 'What is a MAC address? How does it differ from an IP address?', difficulty: 'Beginner' },
    { question: 'What is DNS (Domain Name System) and what does it do?', difficulty: 'Beginner' },
    { question: 'Compare TCP (Transmission Control Protocol) and UDP (User Datagram Protocol).', difficulty: 'Intermediate' },
    { question: 'Explain the TCP Three-Way Handshake process.', difficulty: 'Intermediate' },
    { question: 'What is DHCP? How does a device get an IP address automatically?', difficulty: 'Intermediate' },
    { question: 'What is HTTP and HTTPS? Why is HTTPS secure (SSL/TLS)?', difficulty: 'Intermediate' },
    { question: 'Explain the difference between symmetric and asymmetric encryption.', difficulty: 'Intermediate' },
    { question: 'What is Subnetting, and why is it used? What is a subnet mask?', difficulty: 'Intermediate' },
    { question: 'What are Firewalls, and how do packet filtering firewalls work?', difficulty: 'Intermediate' },
    { question: 'Explain TCP Congestion Control mechanisms (Slow Start, Congestion Avoidance, Fast Retransmit, Fast Recovery).', difficulty: 'Advanced' },
    { question: 'What is BGP (Border Gateway Protocol) and how does routing across the internet work?', difficulty: 'Advanced' },
    { question: 'Explain the DNS resolution process in detail, covering recursive and authoritative DNS servers.', difficulty: 'Advanced' },
    { question: 'What is NAT (Network Address Translation)? Explain static, dynamic, and PAT.', difficulty: 'Advanced' },
    { question: 'Explain how CDNs (Content Delivery Networks) work and speed up content delivery.', difficulty: 'Advanced' },
    { question: 'Explain the concept of WebSockets and how they differ from HTTP polling.', difficulty: 'Advanced' }
  ],
  'OOP': [
    { question: 'What is Object-Oriented Programming (OOP)? What are its main advantages?', difficulty: 'Beginner' },
    { question: 'Explain the concept of a Class and an Object.', difficulty: 'Beginner' },
    { question: 'What are the four pillars of OOP?', difficulty: 'Beginner' },
    { question: 'Explain Inheritance. What is single inheritance vs multiple inheritance?', difficulty: 'Beginner' },
    { question: 'What is Polymorphism? Contrast compile-time and runtime polymorphism.', difficulty: 'Beginner' },
    { question: 'What is Encapsulation, and how do access specifiers help achieve it?', difficulty: 'Beginner' },
    { question: 'What is Abstraction, and how is it different from Encapsulation?', difficulty: 'Beginner' },
    { question: 'Explain the difference between an Abstract Class and an Interface.', difficulty: 'Intermediate' },
    { question: 'What is a Constructor? Explain default, parameterized, and copy constructors.', difficulty: 'Intermediate' },
    { question: 'Explain the "super" and "this" keywords in object-oriented languages.', difficulty: 'Intermediate' },
    { question: 'What is method overloading and method overriding? Give syntax examples.', difficulty: 'Intermediate' },
    { question: 'What is composition and aggregation? How do they differ from inheritance (IS-A vs HAS-A)?', difficulty: 'Intermediate' },
    { question: 'What is an abstract method? Can a class have abstract methods without being abstract itself?', difficulty: 'Intermediate' },
    { question: 'Explain static binding vs dynamic binding.', difficulty: 'Intermediate' },
    { question: 'Explain the SOLID principles of Object-Oriented Design in detail.', difficulty: 'Advanced' },
    { question: 'What is the Liskov Substitution Principle (LSP)? Give an example of its violation.', difficulty: 'Advanced' },
    { question: 'What is the Dependency Inversion Principle (DIP)? How does it relate to Dependency Injection?', difficulty: 'Advanced' },
    { question: 'Explain the difference between shallow copy and deep copy in object replication.', difficulty: 'Advanced' },
    { question: 'What is the Diamond Problem in multiple inheritance? How do languages like Java or C++ handle it?', difficulty: 'Advanced' },
    { question: 'Explain design patterns. Contrast Creational, Structural, and Behavioral design patterns.', difficulty: 'Advanced' }
  ],
  'DSA': [
    { question: 'What is a Data Structure? Contrast linear vs non-linear data structures.', difficulty: 'Beginner' },
    { question: 'Explain Time Complexity and Space Complexity. What is Big O notation?', difficulty: 'Beginner' },
    { question: 'What is an Array? How is memory allocated for arrays, and what is the lookup time complexity?', difficulty: 'Beginner' },
    { question: 'What is a Singly Linked List? Contrast it with a Doubly Linked List.', difficulty: 'Beginner' },
    { question: 'What is a Stack, and what are its main operations? What is LIFO?', difficulty: 'Beginner' },
    { question: 'What is a Queue? What is FIFO? Name a real-world application.', difficulty: 'Beginner' },
    { question: 'Explain Binary Search. What are its prerequisites and time complexity?', difficulty: 'Beginner' },
    { question: 'What is a Hash Table? How do you resolve hash collisions (chaining vs open addressing)?', difficulty: 'Intermediate' },
    { question: 'What is a Binary Tree? How does it differ from a Binary Search Tree (BST)?', difficulty: 'Intermediate' },
    { question: 'Explain Tree Traversals (Inorder, Preorder, Postorder) and their applications.', difficulty: 'Intermediate' },
    { question: 'What is a Graph? Explain Adjacency Matrix and Adjacency List representations.', difficulty: 'Intermediate' },
    { question: 'Contrast Depth First Search (DFS) and Breadth First Search (BFS) graph traversals.', difficulty: 'Intermediate' },
    { question: 'What is recursion? Explain the call stack and base case concepts.', difficulty: 'Intermediate' },
    { question: 'Explain the sorting algorithms: Merge Sort vs Quick Sort. When is one preferred over the other?', difficulty: 'Intermediate' },
    { question: 'What is Dynamic Programming? Describe memoization vs tabulation with Fibonacci.', difficulty: 'Advanced' },
    { question: 'Explain Dijkstra\'s algorithm for finding shortest paths in a graph.', difficulty: 'Advanced' },
    { question: 'What is an AVL Tree and a Red-Black Tree? Why are they called self-balancing BSTs?', difficulty: 'Advanced' },
    { question: 'What is a Trie data structure, and what are its primary use cases (e.g. autocomplete)?', difficulty: 'Advanced' },
    { question: 'Explain the sliding window technique and when it is useful for resolving array/string problems.', difficulty: 'Advanced' },
    { question: 'What is a Heap (Min-Heap/Max-Heap)? Explain the heapify operation and its time complexity.', difficulty: 'Advanced' }
  ],
  'HTML & CSS': [
    { question: 'What is HTML5, and what are semantic elements?', difficulty: 'Beginner' },
    { question: 'Explain the CSS Box Model (content, padding, border, margin).', difficulty: 'Beginner' },
    { question: 'What is the difference between inline, block, and inline-block elements?', difficulty: 'Beginner' },
    { question: 'What is the purpose of the "alt" attribute on image tags?', difficulty: 'Beginner' },
    { question: 'Explain CSS selectors specificity rules.', difficulty: 'Beginner' },
    { question: 'What is the difference between absolute, relative, fixed, sticky, and static positioning?', difficulty: 'Beginner' },
    { question: 'What are CSS media queries, and how do they support responsive web design?', difficulty: 'Beginner' },
    { question: 'Explain CSS Flexbox layout. Name three container properties and item properties.', difficulty: 'Intermediate' },
    { question: 'What is CSS Grid? Contrast CSS Flexbox vs CSS Grid.', difficulty: 'Intermediate' },
    { question: 'What is the difference between "rem" and "em" units in CSS?', difficulty: 'Intermediate' },
    { question: 'What are CSS pseudo-classes (e.g. :hover) and pseudo-elements (e.g. ::before)?', difficulty: 'Intermediate' },
    { question: 'Explain the difference between cookies, localStorage, and sessionStorage.', difficulty: 'Intermediate' },
    { question: 'What is the critical rendering path in browser loading?', difficulty: 'Intermediate' },
    { question: 'What are preprocessors like SASS/SCSS, and what advantages do they offer over plain CSS?', difficulty: 'Intermediate' },
    { question: 'Explain CSS BEM methodology and its benefits.', difficulty: 'Advanced' },
    { question: 'What is hardware acceleration in CSS animations? How do you trigger it?', difficulty: 'Advanced' },
    { question: 'Explain CSS Houdini and custom layout paint APIs.', difficulty: 'Advanced' },
    { question: 'What is layout thrashing (forced synchronous layout), and how do you avoid it?', difficulty: 'Advanced' },
    { question: 'Explain web accessibility guidelines (WCAG) and ARIA attributes in HTML.', difficulty: 'Advanced' },
    { question: 'How do you optimize CSS and HTML for faster page loads and rendering performance?', difficulty: 'Advanced' }
  ],
  'Python': [
    { question: 'What is Python, and what are its key features?', difficulty: 'Beginner' },
    { question: 'Explain the difference between mutable and immutable data types in Python.', difficulty: 'Beginner' },
    { question: 'What is a list, tuple, set, and dictionary in Python?', difficulty: 'Beginner' },
    { question: 'What is PEP 8, and why is it important?', difficulty: 'Beginner' },
    { question: 'Explain the difference between "is" and "==" in Python.', difficulty: 'Beginner' },
    { question: 'What are list comprehensions, and what is their syntax?', difficulty: 'Beginner' },
    { question: 'What is the difference between range() and xrange() in Python?', difficulty: 'Beginner' },
    { question: 'Explain decorators in Python and write a simple execution-timer decorator.', difficulty: 'Intermediate' },
    { question: 'What are generators in Python? How do they differ from lists? What is the yield keyword?', difficulty: 'Intermediate' },
    { question: 'Explain memory management in Python. How does garbage collection work?', difficulty: 'Intermediate' },
    { question: 'What is *args and **kwargs in Python function parameters?', difficulty: 'Intermediate' },
    { question: 'Explain namespaces and scope resolution rules in Python (LEGB rule).', difficulty: 'Intermediate' },
    { question: 'What is a lambda function in Python? Give an example.', difficulty: 'Intermediate' },
    { question: 'Explain Exception Handling in Python using try, except, else, and finally.', difficulty: 'Intermediate' },
    { question: 'What is the Global Interpreter Lock (GIL) in Python, and how does it impact concurrency?', difficulty: 'Advanced' },
    { question: 'Explain how Python\'s memory manager handles small object allocation (PyMalloc).', difficulty: 'Advanced' },
    { question: 'What is metaclass programming in Python? When would you use a metaclass?', difficulty: 'Advanced' },
    { question: 'Explain context managers and how to implement them using classes or contextlib.', difficulty: 'Advanced' },
    { question: 'Explain the difference between multiprocessing and multithreading in Python under GIL.', difficulty: 'Advanced' },
    { question: 'How does Python handle method resolution order (MRO) in multiple inheritance (C3 linearization)?', difficulty: 'Advanced' }
  ],
  'Git & GitHub': [
    { question: 'What is Git, and what is a Version Control System?', difficulty: 'Beginner' },
    { question: 'Explain the difference between Git and GitHub.', difficulty: 'Beginner' },
    { question: 'What is git init, git add, and git commit?', difficulty: 'Beginner' },
    { question: 'Explain git status, git log, and git diff.', difficulty: 'Beginner' },
    { question: 'What is a branch in Git? How do you create and switch to a branch?', difficulty: 'Beginner' },
    { question: 'What is the purpose of a .gitignore file?', difficulty: 'Beginner' },
    { question: 'Explain git clone, git push, and git pull.', difficulty: 'Beginner' },
    { question: 'Explain the difference between git merge and git rebase.', difficulty: 'Intermediate' },
    { question: 'What is a merge conflict, and how do you resolve it?', difficulty: 'Intermediate' },
    { question: 'Explain git stash. When and why would you use it?', difficulty: 'Intermediate' },
    { question: 'What is the difference between git fetch and git pull?', difficulty: 'Intermediate' },
    { question: 'What is cherry-pick in Git? Give a scenario where you would use it.', difficulty: 'Intermediate' },
    { question: 'What is git reset and git revert? Contrast their effects.', difficulty: 'Intermediate' },
    { question: 'What are pull requests (PRs) and forks on GitHub?', difficulty: 'Intermediate' },
    { question: 'Explain Git branching strategies like Git Flow, GitHub Flow, and Trunk-Based Development.', difficulty: 'Advanced' },
    { question: 'What is git reflog? How can it save you from losing commits?', difficulty: 'Advanced' },
    { question: 'Explain git bisect. How does it help locate buggy commits?', difficulty: 'Advanced' },
    { question: 'What are Git Hooks, and how can they be used to enforce code styling or testing?', difficulty: 'Advanced' },
    { question: 'Explain the internal data model of Git (blobs, trees, commits, and tags).', difficulty: 'Advanced' },
    { question: 'How do you clean up your local commit history (squashing) before pushing to a remote repository?', difficulty: 'Advanced' }
  ],
  'Docker': [
    { question: 'What is Docker? What problem does it solve?', difficulty: 'Beginner' },
    { question: 'Compare virtual machines (VMs) and containers.', difficulty: 'Beginner' },
    { question: 'What is a Dockerfile, a Docker Image, and a Docker Container?', difficulty: 'Beginner' },
    { question: 'Explain basic Docker commands: docker build, docker run, docker ps, and docker stop.', difficulty: 'Beginner' },
    { question: 'What is Docker Hub?', difficulty: 'Beginner' },
    { question: 'Explain the difference between docker run and docker start.', difficulty: 'Beginner' },
    { question: 'What is a container port mapping, and how do you define it?', difficulty: 'Beginner' },
    { question: 'Explain Docker Volumes. Why are they necessary? Contrast bind mounts and volumes.', difficulty: 'Intermediate' },
    { question: 'Explain Docker Networking. What are default networks (bridge, host, none)?', difficulty: 'Intermediate' },
    { question: 'What is Docker Compose, and how is it configured in a docker-compose.yml file?', difficulty: 'Intermediate' },
    { question: 'What are the differences between CMD and ENTRYPOINT instructions in a Dockerfile?', difficulty: 'Intermediate' },
    { question: 'What is the purpose of the .dockerignore file?', difficulty: 'Intermediate' },
    { question: 'How do you look at logs and exec into a running container?', difficulty: 'Intermediate' },
    { question: 'What are dangling images and volumes, and how do you clean them up?', difficulty: 'Intermediate' },
    { question: 'Explain Docker multi-stage builds. Why are they used?', difficulty: 'Advanced' },
    { question: 'How do you optimize Docker image sizes (e.g. alpine bases, minimizing layers)?', difficulty: 'Advanced' },
    { question: 'Explain the security implications of running containers as root. How do you mitigate this?', difficulty: 'Advanced' },
    { question: 'What is the difference between Docker Swarm and Kubernetes? When to choose which?', difficulty: 'Advanced' },
    { question: 'Explain how container namespaces and cgroups work in the Linux kernel to achieve isolation.', difficulty: 'Advanced' },
    { question: 'How do you orchestrate containerized applications in production for high availability and rolling updates?', difficulty: 'Advanced' }
  ],
  'REST APIs': [
    { question: 'What does REST stand for? What is a REST API?', difficulty: 'Beginner' },
    { question: 'List the main HTTP Methods and explain their purposes.', difficulty: 'Beginner' },
    { question: 'What is the difference between GET and POST requests?', difficulty: 'Beginner' },
    { question: 'Explain HTTP Status Codes categories (1xx, 2xx, 3xx, 4xx, 5xx).', difficulty: 'Beginner' },
    { question: 'What are HTTP headers? Give three examples of request/response headers.', difficulty: 'Beginner' },
    { question: 'What is JSON, and why is it preferred over XML in REST APIs?', difficulty: 'Beginner' },
    { question: 'What is a URI/URL? Give an example of a well-designed RESTful URI.', difficulty: 'Beginner' },
    { question: 'Explain the concept of statelessness in REST architecture.', difficulty: 'Intermediate' },
    { question: 'What is the difference between PUT and PATCH methods?', difficulty: 'Intermediate' },
    { question: 'Explain Idempotency. Which HTTP methods are idempotent and which are not?', difficulty: 'Intermediate' },
    { question: 'How do you version REST APIs? Discuss URI versioning vs header versioning.', difficulty: 'Intermediate' },
    { question: 'Explain CORS (Cross-Origin Resource Sharing). What is a preflight request?', difficulty: 'Intermediate' },
    { question: 'How do you secure REST APIs? (Token authentication, OAuth2, API Keys).', difficulty: 'Intermediate' },
    { question: 'What is pagination, filtering, and sorting? How do you implement them in REST APIs?', difficulty: 'Intermediate' },
    { question: 'Explain HATEOAS (Hypermedia As The Engine Of Application State) and its role in REST maturity.', difficulty: 'Advanced' },
    { question: 'What is rate limiting, and how do you implement token bucket algorithms for APIs?', difficulty: 'Advanced' },
    { question: 'Explain REST API caching. What is the role of Cache-Control, ETag, and Last-Modified headers?', difficulty: 'Advanced' },
    { question: 'Compare REST APIs vs GraphQL vs gRPC. When should you use which?', difficulty: 'Advanced' },
    { question: 'How do you design a high-throughput REST API that processes payments reliably and prevents double submission?', difficulty: 'Advanced' },
    { question: 'Explain database transactions in API design. How do you handle rollback across external API integrations?', difficulty: 'Advanced' }
  ],
  'Cloud Computing': [
    { question: 'What is Cloud Computing? Explain IaaS, PaaS, and SaaS.', difficulty: 'Beginner' },
    { question: 'Explain public cloud vs private cloud vs hybrid cloud.', difficulty: 'Beginner' },
    { question: 'What is AWS, GCP, and Azure?', difficulty: 'Beginner' },
    { question: 'What is virtualization in cloud computing?', difficulty: 'Beginner' },
    { question: 'What is a cloud database? Give an example of SQL and NoSQL in AWS.', difficulty: 'Beginner' },
    { question: 'What is cloud storage? Contrast block storage and object storage.', difficulty: 'Beginner' },
    { question: 'What is an Availability Zone (AZ) and a Region in AWS/GCP?', difficulty: 'Beginner' },
    { question: 'Explain Amazon EC2 (Elastic Compute Cloud). What are instance types?', difficulty: 'Intermediate' },
    { question: 'Explain Amazon S3 (Simple Storage Service). What are its features?', difficulty: 'Intermediate' },
    { question: 'What is a Load Balancer, and how does it distribute traffic across servers?', difficulty: 'Intermediate' },
    { question: 'What is Auto-Scaling, and how does it handle traffic spikes in the cloud?', difficulty: 'Intermediate' },
    { question: 'What is Serverless Architecture? Explain AWS Lambda or Cloud Functions.', difficulty: 'Intermediate' },
    { question: 'Explain VPC (Virtual Private Cloud). What are subnets, internet gateways, and NAT gateways?', difficulty: 'Intermediate' },
    { question: 'What is Identity and Access Management (IAM)? Why is it crucial?', difficulty: 'Intermediate' },
    { question: 'Explain the Shared Responsibility Model in cloud computing security.', difficulty: 'Advanced' },
    { question: 'What is Infrastructure as Code (IaC)? Explain tools like Terraform or CloudFormation.', difficulty: 'Advanced' },
    { question: 'Explain multi-region deployment. How do you achieve active-active configurations?', difficulty: 'Advanced' },
    { question: 'What is edge computing and CDN? How does Amazon CloudFront reduce latency?', difficulty: 'Advanced' },
    { question: 'Explain data archiving in the cloud. Contrast hot, cool, and cold storage options.', difficulty: 'Advanced' },
    { question: 'How do you design a highly available, fault-tolerant, and cost-effective web app on AWS?', difficulty: 'Advanced' }
  ],
  'System Design': [
    { question: 'What is System Design? Why is it important for software engineering?', difficulty: 'Beginner' },
    { question: 'Explain Vertical Scaling (Scaling Up) vs Horizontal Scaling (Scaling Out).', difficulty: 'Beginner' },
    { question: 'What is a Load Balancer? Name two algorithms used for load balancing.', difficulty: 'Beginner' },
    { question: 'What is Caching? What problems does it solve?', difficulty: 'Beginner' },
    { question: 'What is a Monolithic Architecture vs a Microservices Architecture?', difficulty: 'Beginner' },
    { question: 'What is latency vs throughput in systems performance?', difficulty: 'Beginner' },
    { question: 'What is single point of failure (SPOF)? How do you eliminate it?', difficulty: 'Beginner' },
    { question: 'Explain Database Sharding (Horizontal Partitioning) vs Replication.', difficulty: 'Intermediate' },
    { question: 'Explain the CAP Theorem (Consistency, Availability, Partition Tolerance) and its significance.', difficulty: 'Intermediate' },
    { question: 'What is a Content Delivery Network (CDN), and how does it work?', difficulty: 'Intermediate' },
    { question: 'What are Message Queues (e.g. RabbitMQ, Kafka), and why do we use them for asynchronous tasks?', difficulty: 'Intermediate' },
    { question: 'Explain DNS routing and global load balancing.', difficulty: 'Intermediate' },
    { question: 'What is Cache Eviction? Explain LRU, LFU, and FIFO cache eviction policies.', difficulty: 'Intermediate' },
    { question: 'Explain the difference between SQL and NoSQL in system design. When to use which?', difficulty: 'Intermediate' },
    { question: 'Explain Consistent Hashing and how it is used in distributed caching systems (like Memcached).', difficulty: 'Advanced' },
    { question: 'What is event-driven architecture? How do you maintain data consistency using the Saga Pattern?', difficulty: 'Advanced' },
    { question: 'Explain rate limiting algorithms (Token Bucket, Leaky Bucket, Sliding Window Log).', difficulty: 'Advanced' },
    { question: 'How do you design a URL shortener system (like Bit.ly) for high scale?', difficulty: 'Advanced' },
    { question: 'Explain the design of a real-time chat application (like WhatsApp) covering protocols and connections.', difficulty: 'Advanced' },
    { question: 'How do you design a system to track user locations in real-time (like Uber)?', difficulty: 'Advanced' }
  ],
  'Cyber Security': [
    { question: 'What is the difference between Authentication and Authorization?', difficulty: 'Beginner' },
    { question: 'What is the difference between Encryption and Hashing?', difficulty: 'Beginner' },
    { question: 'What is HTTPS, and how does SSL/TLS encrypt traffic?', difficulty: 'Beginner' },
    { question: 'What are SQL Injection (SQLi) attacks, and how do you prevent them?', difficulty: 'Beginner' },
    { question: 'Explain Cross-Site Scripting (XSS). What are the different types?', difficulty: 'Beginner' },
    { question: 'What is a firewall, and what is its role in security?', difficulty: 'Beginner' },
    { question: 'What is multi-factor authentication (MFA)?', difficulty: 'Beginner' },
    { question: 'Explain Cross-Site Request Forgery (CSRF). How do you prevent it?', difficulty: 'Intermediate' },
    { question: 'What is JWT (JSON Web Token)? Explain its structure and how it is verified.', difficulty: 'Intermediate' },
    { question: 'What is Salting in password hashing? Why is it crucial?', difficulty: 'Intermediate' },
    { question: 'Explain the principle of least privilege (PoLP) in access control.', difficulty: 'Intermediate' },
    { question: 'What are DDoS attacks, and how can they be mitigated?', difficulty: 'Intermediate' },
    { question: 'Explain asymmetric key cryptography vs symmetric key cryptography.', difficulty: 'Intermediate' },
    { question: 'What is phishing, and how do digital signatures protect identity?', difficulty: 'Intermediate' },
    { question: 'Explain OAuth 2.0 and OpenID Connect flows in detail.', difficulty: 'Advanced' },
    { question: 'What is Man-in-the-Middle (MitM) attack? Explain ARP spoofing and DNS poisoning.', difficulty: 'Advanced' },
    { question: 'What is a SQL injection vulnerability in ORM engines? How does it happen?', difficulty: 'Advanced' },
    { question: 'Explain zero-trust network architecture and its core principles.', difficulty: 'Advanced' },
    { question: 'What are session hijacking and session fixation? How do you prevent them?', difficulty: 'Advanced' },
    { question: 'Explain how buffer overflow vulnerabilities work in C/C++ programs and how they are exploited.', difficulty: 'Advanced' }
  ],
  'Agile & DevOps': [
    { question: 'What is Agile software development? What is the Scrum framework?', difficulty: 'Beginner' },
    { question: 'Explain the difference between Scrum and Kanban.', difficulty: 'Beginner' },
    { question: 'What is DevOps, and what problem does it solve?', difficulty: 'Beginner' },
    { question: 'What is CI/CD (Continuous Integration / Continuous Delivery)?', difficulty: 'Beginner' },
    { question: 'What is unit testing vs integration testing vs end-to-end testing?', difficulty: 'Beginner' },
    { question: 'Explain the role of a Product Owner, Scrum Master, and Developer in Scrum.', difficulty: 'Beginner' },
    { question: 'What is a daily standup meeting, sprint planning, and sprint retrospective?', difficulty: 'Beginner' },
    { question: 'Explain Infrastructure as Code (IaC) and its benefits.', difficulty: 'Intermediate' },
    { question: 'Explain Blue-Green deployments vs Canary deployments.', difficulty: 'Intermediate' },
    { question: 'What is the purpose of test-driven development (TDD)?', difficulty: 'Intermediate' },
    { question: 'What are system monitoring and logging tools? (e.g. ELK, Prometheus, Grafana).', difficulty: 'Intermediate' },
    { question: 'Explain GitOps and how it integrates with Kubernetes.', difficulty: 'Intermediate' },
    { question: 'What is container orchestration? Why do we need Kubernetes?', difficulty: 'Intermediate' },
    { question: 'What is technical debt? How does Agile manage it?', difficulty: 'Intermediate' },
    { question: 'Explain the concept of microservices observability (tracing, metrics, logs) in DevOps.', difficulty: 'Advanced' },
    { question: 'Explain Chaos Engineering. Why do companies like Netflix use chaos monkeys?', difficulty: 'Advanced' },
    { question: 'What is shift-left testing? How does it improve software quality?', difficulty: 'Advanced' },
    { question: 'Explain standard DevOps pipelines building, scanning (SAST/DAST), testing, and deployment.', difficulty: 'Advanced' },
    { question: 'How do you design a zero-downtime deployment pipeline for a high-traffic e-commerce application?', difficulty: 'Advanced' },
    { question: 'How does configuration management (Ansible, Chef, Puppet) compare to containerization in DevOps?', difficulty: 'Advanced' }
  ],
  'HR Questions': [
    { question: 'Tell me about yourself. What are your core strengths and how do they align with this role?', difficulty: 'Beginner' },
    { question: 'Why do you want to work for our company?', difficulty: 'Beginner' },
    { question: 'What are your greatest strengths and weaknesses?', difficulty: 'Beginner' },
    { question: 'Why should we hire you?', difficulty: 'Beginner' },
    { question: 'Where do you see yourself in five years?', difficulty: 'Beginner' },
    { question: 'What are your salary expectations?', difficulty: 'Beginner' },
    { question: 'Do you have any questions for us?', difficulty: 'Beginner' },
    { question: 'Describe a situation where you had a conflict with a team member. How did you resolve it?', difficulty: 'Intermediate' },
    { question: 'Tell me about a time you failed or made a mistake on a project. What did you learn?', difficulty: 'Intermediate' },
    { question: 'Describe a time you had to work under a tight deadline. How did you handle the pressure?', difficulty: 'Intermediate' },
    { question: 'How do you handle constructive criticism or negative feedback?', difficulty: 'Intermediate' },
    { question: 'Describe a project you are most proud of. What was your role in its success?', difficulty: 'Intermediate' },
    { question: 'How do you stay updated with the latest technologies and trends?', difficulty: 'Intermediate' },
    { question: 'Explain a scenario where you disagreed with your manager\'s decision. How did you communicate?', difficulty: 'Intermediate' },
    { question: 'Tell me about a time you had to learn a completely new technology in a short time. What was your approach?', difficulty: 'Advanced' },
    { question: 'Describe a situation where a project requirements changed drastically mid-way. How did you adapt?', difficulty: 'Advanced' },
    { question: 'How do you prioritize tasks when managing multiple urgent projects simultaneously?', difficulty: 'Advanced' },
    { question: 'Describe a time you mentored a junior developer or helped a teammate solve a critical blocker.', difficulty: 'Advanced' },
    { question: 'What would you do if you realized a critical bug was deployed to production by your team?', difficulty: 'Advanced' },
    { question: 'How do you foster a collaborative and diverse team culture?', difficulty: 'Advanced' }
  ]
};

module.exports = {
  topicsData,
  questionsData
};
